valor_em_metros = float(input('Digite um valor em metros: '))
valor_em_cm = float(valor_em_metros*100)
valor_em_mm = float(valor_em_metros*1000)
print('Valor em centimetros {}'.format(valor_em_cm))
print('Valor em milimetros {}'.format(valor_em_mm))